name: Auto Merge Branches

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensure all branches are fetched

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Merge main into staging
      if: github.ref == 'refs/heads/main'
      run: |
        git checkout staging
        git pull
        git merge --no-ff main -m "Auto-merge master into staging"
        git push origin staging
        git checkout development
        git pull
        git merge --no-ff staging -m "Auto-merge staging into development"
        git push origin development
      continue-on-error: true  # Continue even if this step fails

    - name: Merge staging into development
      if: github.ref == 'refs/heads/staging'
      run: |
        git checkout development
        git pull
        git merge --no-ff staging -m "Auto-merge staging into development"
        git push origin development
      continue-on-error: true  # Continue even if this step fails

    - name: Send Slack notification if merge fails
      if: failure()
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        REPOSITORY: ${{ github.repository }}
        RUN_ID: ${{ github.run_id }}
      run: |
        REPO_URL="https://github.com/$REPOSITORY"
        WORKFLOW_URL="$REPO_URL/actions/runs/$RUN_ID"
        MESSAGE="Merge failed in [${REPOSITORY}] ($REPO_URL). Check the [workflow run] ($WORKFLOW_URL) for details!"
        curl -X POST -H 'Content-type: application/json' --data \
        "{\"text\":\"$MESSAGE\"}" \
        $SLACK_WEBHOOK_URL

