name: Auto Merge Branches

on:
  push:
    branches:
      - main
      - staging

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Merge main into staging
      if: github.ref == 'refs/heads/main'
      run: |
        git fetch --unshallow
        git checkout staging
        git pull
        git merge --no-ff main -m "Auto-merge master into staging"
        git push

    - name: Merge staging into development
      if: github.ref == 'refs/heads/staging'
      run: |
        git fetch
        git checkout development
        git merge staging --allow-unrelated-histories
        git push origin development
